### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by Moep90** [lazyfrosch/icinga2-telegram#2]
Moin, ich habe nun zum zweiten mal (vermutlich falsch) die Notifications wie von dir beschrieben implementiert. Ich finde den Fehler allerdings nicht...

User.conf

> object User "Vorname Nachname" {
>     import "Administrator"
> 
>     display_name = "Benutzername"
>     states = [ Down ]
>     types = [
>         Acknowledgement,
>         Custom,
>         FlappingEnd,
>         FlappingStart,
>         Problem,
>         Recovery
>     ]
>     vars.telegram_chat_id = "chatID"
> }

Notification:
> object NotificationCommand "telegram-host-notification" {
>     import "plugin-notification-command"
>     command = [ "/etc/icinga2/scripts/telegram-host-notification.sh" ]
>     timeout = 1m
>     arguments += {
>         HOSTADDRESS = "$address$"
>         HOSTALIAS = "$host.display_name$"
>         HOSTDISPLAYNAME = "$host.display_name$"
>         HOSTNAME = "$host.name$"
>         HOSTOUTPUT = "$host.output$"
>         HOSTSTATE = "$host.state$"
>         ICINGAWEB2_URL = "https://xyz/icingaweb2"
>         LONGDATETIME = "$icinga.long_date_time$"
>         NOTIFICATIONAUTHORNAME = "$notification.author$"
>         NOTIFICATIONCOMMENT = "$notification.comment$"
>         NOTIFICATIONTYPE = "$notification.type$"
>         TELEGRAM_BOT_TOKEN = "BOT:Token"
>         TELEGRAM_CHAT_ID = "$user.vars.telegram_chat_id$"
>     }
> }

notification_apply.conf

> apply Notification "telegram-host-notification" to Host {
>     import "tmpl_host-telegram"
> 
>     assign where match("*", host.name)
>     states = [ Down ]
>     types = [
>         Acknowledgement,
>         Custom,
>         DowntimeEnd,
>         DowntimeStart,
>         FlappingStart,
>         Problem,
>         Recovery
>     ]
>     users = [ "Vorname Nachname" ]
> }

icinga debug:

> notice/Process: PID 3176 ('/etc/icinga2/scripts/telegram-host-notification.sh' 'HOSTADDRESS' 'xyz' 'HOSTALIAS' 'xyz' 'HOSTDISPLAYNAME' 'xyz' 'HOSTNAME' 'xyz' 'HOSTOUTPUT' 'SSH OK - OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8 (protocol 2.0) ' 'HOSTSTATE' 'UP' 'ICINGAWEB2_URL' 'https://xyz/icingaweb2' 'LONGDATETIME' '2017-01-16 09:32:15 +0100' 'NOTIFICATIONAUTHORNAME' 'icingaweb2admin' 'NOTIFICATIONCOMMENT' 'dsafasd' 'NOTIFICATIONTYPE' 'CUSTOM' 'TELEGRAM_BOT_TOKEN' 'bot:token' 'TELEGRAM_CHAT_ID' 'chatID') terminated with exit code 0

Der Output sieht für mich Okay aus und wenn ich händisch die Variablen im Script setze, funktioniert es auch.

**Comment by lazyfrosch** [comment]
Are you sure the notification filters are what you expecting them to do?

I'm still using my script without any problem.

You should probably debug log what request is actually send to Telegram's API `curl -v ... > /tmp/curl.log 2>&1`

**Comment by Moep90** [comment]
The Problem is that icinga2-director awaiting arguments instead of env which your script awaits.
