### ISSUE TITLE
Send only CUSTOM notifycation

### ISSUE THREAD

**Issue by novikov3278** [lazyfrosch/icinga2-telegram#3]
Hello! Thank you for this very precious script!

Set up according to your instructions. If I send a notification from the Icinga2 web interface, notifications are delivered to the telegram channel only if you set the "forced" option. In this case the bot gets notified CUSTOM. Other types of notifications (DOWN, UP, Warning) cannot be delivered, and there is nothing in logs. Help please. 

```
object User "telegram_bot" {
  import "generic-user"
  display_name = "bot"
  states = [ OK, Warning, Critical ]
  types = [ Problem, Recovery ]
  vars.telegram_chat_id = "ID"
```

**Comment by lazyfrosch** [comment]
Well you haven't enabled the CUSTOM notification type, see [Notification Filters by State and Type](https://www.icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#notification-filters-by-state-and-type)
