### ISSUE TITLE
Issues with UNKNOWN States

### ISSUE THREAD

**Issue by madmax01** [lazyfrosch/icinga2-telegram#4]
Hello,

i'am not sure how to fix this.

But from time to time i'am getting Unknown Alerts over Mail.  But UNKNOWN Alert is not going through Telegram Notification.   all other States seems going through > as i see Critical/Warning/OK are fine

Just the UNKNOWN not working somehow.

i tried to change the Service template  same way like email

```icinga2
template Notification "telegram-service-notification" {
  command = "telegram-service-notification"
  states = [ OK, Warning, Critical, Unknown ]
  types = [ Problem, Acknowledgement, Recovery, Custom,
            FlappingStart, FlappingEnd,
            DowntimeStart, DowntimeEnd, DowntimeRemoved ]


  vars += {
    // notification_icingaweb2url = "https://www.example.com/icingaweb2"
    // notification_from = "Icinga 2 Service Monitoring <icinga@example.com>"
    notification_logtosyslog = false
  }

  period = "24x7"
}
```

Anything special to do?

**Comment by lazyfrosch** [comment]
UNKNOWN states work fine for me, there should not be any difference, since the states are text-only for the telegram script.

Maybe your "telegram" user has additional filters?
