### ISSUE TITLE
check if api.telegram.org is reachable before sending

### ISSUE THREAD

**Issue by MarcusCaepio** [lazyfrosch/icinga2-telegram#6]
Hi,
I am using your script for my raspi at home to monitor my internet connection with icinga2.
Unfortunately, when the internet connection is down, the notification is lost. 
So the script should be able to check, if api.telegram.org is reachable, before sending the notification and if not, should stay in a loop, till it's reachable again.
I tried to execute a 
```
until ping -4 -c 1 api.telegram.org
do
        sleep 10
done
```
before the curl, but this seems to be not the best way. any other ideas?

cheers,
Marcus

**Comment by lazyfrosch** [comment]
Well the best idea is the script in a better language to handle timeout and retries on HTTP base.

**Comment by MarcusCaepio** [comment]
Maybe I will try my luck in python, when I got time for it ^^
